from typing import List, Dict, Tuple, Optional

# ---------------------------------------------------------------------------
# Task definitions
# ---------------------------------------------------------------------------
TASKS = [
    {
        "id": "simple_select",
        "difficulty": "easy",
        "question": (
            "List the full name and city of every customer from the United States. "
            "Order the results alphabetically by name."
        ),
        "hint": "Look at the customers table. Filter by country = 'United States'.",
    },
    {
        "id": "join_aggregation",
        "difficulty": "medium",
        "question": (
            "What is the total revenue generated by each product category? "
            "Show the category name and total revenue, ordered from highest to lowest revenue."
        ),
        "hint": (
            "Join order_items with products on product_id. "
            "Revenue = SUM(quantity * unit_price). GROUP BY category."
        ),
    },
    {
        "id": "window_ranking",
        "difficulty": "hard",
        "question": (
            "For each customer who has placed at least one order, show their name, "
            "their most recent order date, and their rank by total spending "
            "(rank 1 = highest total spending). Order the results by rank."
        ),
        "hint": (
            "Use RANK() OVER (ORDER BY total_spent DESC) — supported in SQLite 3.25+. "
            "Or use a correlated subquery: "
            "SELECT COUNT(*) + 1 FROM ... WHERE total > current_total."
        ),
    },
]


def get_task_by_id(task_id: str) -> dict:
    for t in TASKS:
        if t["id"] == task_id:
            return t
    raise ValueError(f"Unknown task: {task_id!r}")


# ---------------------------------------------------------------------------
# Grader: simple_select
# ---------------------------------------------------------------------------
_US_NAMES = {
    "alice johnson", "bob smith", "carol white",
    "grace lee", "ivy chen", "jack taylor",
}
_US_CITIES = {
    "new york", "los angeles", "chicago",
    "houston", "san francisco", "miami",
}


def grade_simple_select(
    rows: List[dict],
    columns: List[str],
    error: Optional[str],
) -> Tuple[float, str]:
    """
    Expected: 6 US customers — name + city — ordered alphabetically by name.
    """
    if error:
        return 0.0, f"Query error: {error}"
    if not rows:
        return 0.0, "No rows returned. Check your WHERE clause and table name."

    returned_names = {str(r.get("name", "")).lower() for r in rows}
    returned_cities = {str(r.get("city", "")).lower() for r in rows}

    # Try alternate column names
    if not returned_names - {""} :
        for col in columns:
            if "name" in col.lower():
                returned_names = {str(r.get(col, "")).lower() for r in rows}
                break
    if not returned_cities - {""}:
        for col in columns:
            if "city" in col.lower():
                returned_cities = {str(r.get(col, "")).lower() for r in rows}
                break

    name_overlap = len(returned_names & _US_NAMES) / len(_US_NAMES)
    city_overlap = len(returned_cities & _US_CITIES) / len(_US_CITIES)

    # Bonus for correct alphabetical ordering
    name_col = next((c for c in columns if "name" in c.lower()), None)
    ordered = False
    if name_col and len(rows) > 1:
        names = [str(r.get(name_col, "")) for r in rows]
        ordered = names == sorted(names)

    base_score = name_overlap * 0.5 + city_overlap * 0.4
    if ordered and base_score > 0.5:
        base_score = min(1.0, base_score + 0.1)

    if base_score >= 0.95:
        return 1.0, (
            "Perfect! All 6 US customers returned with correct cities, ordered alphabetically."
        )
    elif base_score >= 0.7:
        return round(base_score, 2), (
            f"Mostly correct. Name coverage: {name_overlap:.0%}, "
            f"city coverage: {city_overlap:.0%}."
        )
    elif base_score >= 0.3:
        return round(base_score, 2), (
            "Partial result. Check your WHERE clause and column selection."
        )
    else:
        return 0.1, "Very few correct results. Re-read the question and schema carefully."


# ---------------------------------------------------------------------------
# Grader: join_aggregation
# ---------------------------------------------------------------------------
_EXPECTED_CATEGORIES = {"electronics", "clothing", "books"}


def grade_join_aggregation(
    rows: List[dict],
    columns: List[str],
    error: Optional[str],
) -> Tuple[float, str]:
    """
    Expected: 3 rows — Electronics (highest), Clothing, Books (lowest).
    Agent must JOIN order_items with products and GROUP BY category.
    """
    if error:
        return 0.0, f"Query error: {error}"
    if not rows:
        return 0.0, "No rows returned. You need to JOIN order_items with products."

    # Find category and revenue columns
    cat_col = next(
        (c for c in columns if "cat" in c.lower()),
        None,
    )
    rev_col = next(
        (c for c in columns if any(x in c.lower() for x in ["rev", "total", "sum", "amount", "sales"])),
        None,
    )

    if not cat_col or not rev_col:
        return 0.2, (
            "Cannot identify category or revenue columns. "
            "Alias them as 'category' and 'total_revenue' in your SELECT."
        )

    returned_cats = {str(r.get(cat_col, "")).lower() for r in rows}
    cat_coverage = len(returned_cats & _EXPECTED_CATEGORIES) / len(_EXPECTED_CATEGORIES)

    # Electronics should have the highest revenue → should be first row when ordered DESC
    first_cat = str(rows[0].get(cat_col, "")).lower() if rows else ""
    correct_order = first_cat == "electronics"

    all_three = cat_coverage >= 0.99

    if all_three and correct_order:
        return 1.0, "Excellent! All 3 categories with correct revenue, ordered highest first."
    elif all_three:
        return 0.75, (
            "All 3 categories present but not sorted highest-to-lowest. "
            "Add ORDER BY total_revenue DESC."
        )
    elif cat_coverage >= 0.66:
        return 0.5, (
            f"Found {int(round(cat_coverage * 3))}/3 categories. "
            "Check your JOIN condition and GROUP BY clause."
        )
    else:
        return 0.2, (
            "Missing categories. Join order_items with products on product_id, "
            "then GROUP BY products.category."
        )


# ---------------------------------------------------------------------------
# Grader: window_ranking
# ---------------------------------------------------------------------------

def grade_window_ranking(
    rows: List[dict],
    columns: List[str],
    error: Optional[str],
) -> Tuple[float, str]:
    """
    Expected: all customers who have placed orders, with:
      - customer name
      - most recent order date
      - rank by total spending (rank 1 = highest)
    Results ordered by rank ascending.
    """
    if error:
        return 0.0, f"Query error: {error}"
    if not rows:
        return 0.0, "No rows returned. Try aggregating orders per customer."

    name_col = next((c for c in columns if "name" in c.lower()), None)
    rank_col = next((c for c in columns if "rank" in c.lower()), None)
    date_col = next(
        (c for c in columns if "date" in c.lower() or "recent" in c.lower()),
        None,
    )

    score = 0.0
    feedback_parts: List[str] = []

    if name_col:
        score += 0.15
        feedback_parts.append("customer names present")

    if rank_col:
        ranks = []
        for r in rows:
            v = r.get(rank_col)
            if v is not None:
                try:
                    ranks.append(int(v))
                except (ValueError, TypeError):
                    pass
        if 1 in ranks:
            score += 0.35
            feedback_parts.append("rank column present with rank 1")
        else:
            score += 0.15
            feedback_parts.append("rank column present but rank 1 missing")

    if date_col:
        score += 0.2
        feedback_parts.append("order date column present")

    # Rows should be ordered by rank ascending
    if rank_col and len(rows) > 1:
        rank_vals = []
        for r in rows:
            try:
                rank_vals.append(int(r.get(rank_col, 999)))
            except (ValueError, TypeError):
                pass
        if rank_vals and rank_vals == sorted(rank_vals):
            score += 0.3
            feedback_parts.append("results ordered by rank correctly")

    score = min(1.0, score)

    if score >= 0.9:
        return 1.0, "Excellent! Correct ranking with proper ordering by rank."
    elif score >= 0.5:
        return round(score, 2), "Good progress: " + ", ".join(feedback_parts) + "."
    elif score > 0:
        return round(score, 2), (
            "Partial credit: " + ", ".join(feedback_parts) + ". Keep refining."
        )
    else:
        return 0.1, (
            "Incorrect. Use RANK() OVER (ORDER BY total_spent DESC) or a correlated "
            "subquery to compute ranks. Include name, most recent date, and rank."
        )
